### PR TITLE
Add DPDK 22.11 and bump other DPDK release

### PR DESCRIPTION
**Pull request by clementperon**

### CODE REVIEW

**Comment by seladb** [comment]
@clementperon I think we should only support DPDK LTS versions, the latest is 22.11. It's very hard to keep up with every version they release every 3 months, mostly because they keep breaking their API 😕 

Also - CI won't pass before we merge https://github.com/seladb/PcapPlusPlus/pull/1186, so maybe we can wait with it a little

**Comment by clementperon** [comment]
> @clementperon I think we should only support DPDK LTS versions, the latest is 22.11. It's very hard to keep up with every version they release every 3 months, mostly because they keep breaking their API 😕
> 
> Also - CI won't pass before we merge [seladb/PcapPlusPlus#1186](https://github.com/seladb/PcapPlusPlus/pull/1186), so maybe we can wait with it a little

Yes agree that we should only have in CI the LTS but how do you test that the MR is fixing properly things ?

**Comment by clementperon** [comment]
> > > @clementperon I think we should only support DPDK LTS versions, the latest is 22.11. It's very hard to keep up with every version they release every 3 months, mostly because they keep breaking their API 😕
> > > Also - CI won't pass before we merge [seladb/PcapPlusPlus#1186](https://github.com/seladb/PcapPlusPlus/pull/1186), so maybe we can wait with it a little
> > 
> > 
> > Yes agree that we should only have in CI the LTS but how do you test that the MR is fixing properly things ?
> 
> That's a good question :) Maybe we should not add the new docker to CI so it won't fail? We can probably build it locally to test the PR... what do you think?

To me, These dockers are "reference machines" where Pcap++ should work, the test here is more to say:  "actually Pcap++ is not supported on this machine" but not that this Docker machine is wrong.

**Comment by seladb** [comment]
@clementperon the problem is that if the test fails, the image will not be pushed to DockerHub.

Also - maybe remove DPDK 23.03 and DPDK 23.07?

**Review by seladb — APPROVED** [review]

**Pull request merged**
