### PR TITLE
Support ubuntu24

### PR DESCRIPTION
**Pull request by tigercosmos**
Original PR at https://github.com/seladb/PcapPlusPlus-DockerImages/pull/45, moved to here.

### CODE REVIEW

**Comment by tigercosmos** [comment]
@clementperon Any idea?
```
#8 39.53 Red Hat Universal Base Image 9 (RPMs) - BaseOS  119 kB/s | 3.8 kB     00:00    
#8 39.56 Red Hat Universal Base Image 9 (RPMs) - AppStre 147 kB/s | 4.2 kB     00:00    
#8 39.59 Red Hat Universal Base Image 9 (RPMs) - CodeRea 151 kB/s | 4.2 kB     00:00    
#8 41.48 Dependencies resolved.
#8 41.48 Nothing to do.
#8 41.48 Complete!
#8 41.76 Updating Subscription Management repositories.
#8 43.03 Last metadata expiration check: 0:00:03 ago on Mon Jul 22 00:13:41 2024.
#8 43.18 No match for argument:  
#8 43.20 Error: Unable to find a match:  
#8 ERROR: process "/bin/sh -c /rhel_install.sh && rm /rhel_install.sh" did not complete successfully: exit code: 1
------
```

**Comment by clementperon** [comment]
@tigercosmos I think the package doesn't exist no ?

**Comment by clementperon** [comment]
@tigercosmos sorry I don't have an idea. I could try to push it and see

**Review by clementperon — APPROVED** [review]

**Comment by tigercosmos** [comment]
That's cool, because I think the same logic of installation works in GitHub CI though.

**Comment by seladb** [comment]
> That's cool, because I think the same logic of installation works in GitHub CI though.

@tigercosmos we should remove `python3-virtualenv` from `rhel_install.sh` because venv is already installed:

```sh
seladb@ubuntu22:~$ sudo docker run -it redhat/ubi9:9.4
[root@73584ffa93ad /]# python3 -m venv .venv
[root@73584ffa93ad /]# source .venv/bin/activate
(.venv) [root@73584ffa93ad /]# 
```

**Review by seladb — APPROVED** [review]

**Pull request merged**
