### PR TITLE
Add google benchmark to ubuntu 2204 and 2404

### PR DESCRIPTION
**Pull request by egecetin**
Requirement for https://github.com/seladb/PcapPlusPlus/pull/1392

### CODE REVIEW

**Comment by clementperon** [comment]
In my projects. I usually see benchmark as 3rd party library included in the project. 

Some distro will not have this as system package and the version could also be a strong requirement.
Also benchmark is very quick to compile.

**Comment by egecetin** [comment]
@clementperon Yes, I saw it mostly as 3rd party too, but which one is better in your opinion? Just FetchContent the google benchmark or first check system and fetch if it does not exist?

**Comment by clementperon** [comment]
I would tend to say always fetch content the Google benchmark

**Comment by egecetin** [comment]
@clementperon Thanks, I'll update the main PR

**Pull request closed without merging**
