### PR TITLE
rhel: use licensing manager

### PR DESCRIPTION
**Pull request by clementperon**

### CODE REVIEW

**Comment by clementperon** [comment]
@seladb REDHAT_USERNAME and REDHAT_PASSWORD must be set has secrets in environment

**Comment by seladb** [comment]
> @seladb REDHAT_USERNAME and REDHAT_PASSWORD must be set has secrets in environment

@clementperon I now added them as secrets in both `PcapPlusPlus-DockerImages` and `PcapPlusPlus` repos (previously it was just in `PcapPlusPlus-DockerImages`). Do you think it'll work now?

**Comment by clementperon** [comment]
@selab only on Docker images is required. I have attached a screenshot of my config on my repo.
Screenshot_20240616-003610

**Comment by seladb** [comment]
oh I understand, you need these secrets on your fork?
Let me send you them in slack

**Comment by clementperon** [comment]
Hi, no on my fork the CI is fine 
https://github.com/clementperon/PcapPlusPlus-DockerImages/actions/runs/9526906550

**Comment by seladb** [comment]
> Hi, no on my fork I use my credential and the CI is fine https://github.com/clementperon/PcapPlusPlus-DockerImages/actions/runs/9526906550

So I'm not sure why it's not working in this PR. I added the secrets in this repo 🤔 

image

**Comment by clementperon** [comment]
@seladb 
image

I think i'm not a Collaborator of this repo no ?

**Comment by seladb** [comment]
You are a collaborator:

image

**Pull request closed without merging**
